services:
  - type: web
    name: qulay-backend
    runtime: node
    plan: starter
    buildCommand: npm ci --fetch-retries=5 --fetch-retry-mintimeout=20000 --fetch-retry-maxtimeout=120000 && npm run build && npm run prisma:migrate:deploy && npm run prisma:seed
    startCommand: npm start
    healthCheckPath: /api/v1/health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.22.0
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: https://qulay-d.vercel.app,http://localhost:5173
      - key: FRONTEND_RESET_URL
        value: https://qulay-d.vercel.app/reset-password
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: UPLOAD_DIR
        value: /var/data/qulay-uploads
      - key: UPLOAD_PUBLIC_BASE_URL
        value: https://qulayd-backend.onrender.com
    disk:
      name: qulay-uploads
      mountPath: /var/data
      sizeGB: 1
